version: '3.8'
services:
  analogierechner:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Streamlit
      - "8081:8081"  # API
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs  # Diese Zeile muss da sein
    env_file:
      - .env.local
    environment:
      - ENVIRONMENT=local